/**
 * TeleDOM v4 — The 100+ Improvement Matrix (REGISTRY, not a static doc).
 *
 * Every improvement is a real, engineering-valuable delta beyond the v4
 * roadmap baseline, with: problem, baseline limitation, external evidence,
 * why it matters, architecture, affected modules, complexity, risk,
 * benefit, tests, benchmark, security implications, version target,
 * priority, and implementation status. The docs/intelligence/IMPROVEMENTS.md
 * document is GENERATED from this registry, and a test asserts ≥100
 * distinct non-trivial improvements — feature inflation is structurally
 * rejected.
 */

export type ImprovementStatus =
  | 'IMPLEMENTED' | 'PARTIAL' | 'DEFERRED-external-infrastructure'
  | 'DEFERRED-platform-limit' | 'RESEARCH-ONLY';

export interface Improvement {
  id: string;
  title: string;
  category: string;
  problem: string;
  baselineLimitation: string;
  externalEvidence: string;
  why: string;
  architecture: string;
  modules: string[];
  complexity: 'low' | 'medium' | 'high';
  risk: 'low' | 'medium' | 'high';
  benefit: string;
  tests: string;
  benchmark?: string;
  security: string;
  version: string;
  priority: 'P0' | 'P1' | 'P2' | 'P3';
  status: ImprovementStatus;
}

const E = (
  id: string, title: string, category: string,
  problem: string, baselineLimitation: string, externalEvidence: string, why: string,
  architecture: string, modules: string[], complexity: Improvement['complexity'],
  risk: Improvement['risk'], benefit: string, tests: string, security: string,
  version: string, priority: Improvement['priority'], status: ImprovementStatus,
  benchmark?: string,
): Improvement => ({
  id, title, category, problem, baselineLimitation, externalEvidence, why,
  architecture, modules, complexity, risk, benefit, tests, benchmark, security,
  version, priority, status,
});

export const IMPROVEMENTS: Improvement[] = [
  // ---- Temporal intelligence (1-12) ----
  E('T01', 'Atomic event identity allocation', 'temporal', 'event.sequence and the sequence embedded in event.id could diverge (double-advance bug)', 'generateEventId() advanced the counter a second time', 'Roadmap §13 P0; rrweb order-sensitivity; direct code inspection of DOMMutationObserver', 'A temporal/forensic system whose event identity is inconsistent cannot guarantee ordering or replay', 'Single-step allocation: allocateSequence() + eventIdFor(seq) in EventMesh; legacy SequenceCounter now accepts explicit seq', ['kernel/events', 'core/sequence-counter', 'core/* call sites'], 'medium', 'high', 'Invariant event.sequence === seq-in-id holds for every event; legacy behavior preserved', 'tests/intelligence/kernel.test.ts (invariant test)', 'none', '4.0', 'P0', 'IMPLEMENTED', 'admission benchmark'),
  E('T02', 'Hash-chained tamper evidence', 'temporal', 'No cryptographic integrity over recorded sessions', 'Sessions were plain JSON files; silent tampering undetectable', 'Forensic standards; rrweb/openreplay lack chain-of-custody; roadmap §21', 'A forensic platform must PROVE evidence was not modified', 'SHA-256 hash chain per event (h(n)=H(h(n-1)+c(n))) + chain tip verification + restore-time re-verify', ['kernel/integrity', 'kernel/events'], 'medium', 'low', 'Any historical event mutation breaks every subsequent link and is detected', 'tests/intelligence/kernel.test.ts (tamper test)', 'integrity-by-construction', '4.0', 'P0', 'IMPLEMENTED'),
  E('T03', 'Append-only EventMesh with admission control', 'temporal', 'Global event assumptions: duplicates, reorder, gaps and corrupt input unhandled', 'Recorder pushed events into arrays; no dedup, no gap detection, no corruption rejection', 'Playwright MCP crash-recovery issues; Chrome DevTools MCP page-state desync reports', 'The browser is an unreliable producer; the kernel must guarantee a coherent stream', 'append() = integrity verify → dedup (id + idempotency) → gap detection → late admission → chain extend', ['kernel/events'], 'high', 'medium', 'Duplicate collapse, gap accounting, late-event flags, corrupt rejection — all observable via stats()', 'tests/intelligence/kernel.test.ts (6 admission tests)', 'corrupt envelopes never merged', '4.0', 'P0', 'IMPLEMENTED'),
  E('T04', 'Hybrid logical/wall clock separation', 'temporal', 'performance.now() resolution was conflated with replay latency in marketing claims', 'Sub-millisecond claim without benchmark separation', 'Roadmap §37 "never conflate timestamp resolution with latency"', 'Ordering must never depend on wall clock (NTP jumps); latency claims must be measured', 'HybridClock: monotonic logical ticks + wall track + regression diagnostic; resolution reported separately', ['kernel/clock'], 'low', 'low', 'Deterministic ordering; honest resolution-vs-latency reporting', 'tests/intelligence/kernel.test.ts (monotonic + regression)', 'none', '4.0', 'P0', 'IMPLEMENTED', 'benchmarks column separation'),
  E('T05', 'State(T) reconstruction with memoization + budgets', 'temporal', 'Reconstruction unbounded; no budget, no memoization', 'StateReconstructor replayed all events from checkpoint with LRU only', 'Large-session memory growth reports in MCP trackers', 'Reconstruction must degrade gracefully under huge streams', 'Nearest-checkpoint + delta replay + memo cache + maxReconstructionMs budget with DEGRADED flag', ['temporal/queries'], 'medium', 'medium', 'Bounded reconstruction with honest degraded results', 'tests/intelligence/temporal.test.ts (stateAt meta)', 'reconstruction benchmark p50/p95/p99', '4.0', 'P0', 'IMPLEMENTED'),
  E('T06', 'Diff(T1,T2) across all state dimensions', 'temporal', 'No whole-state diff between arbitrary times', 'diff_dom compared DOM only at recorded timestamps', 'rrweb DOM-only diffing; roadmap §14 Diff(T1,T2)', 'Agents ask "what changed between two moments" across ALL signals', 'Dimension-level diff computed from two reconstructions with added/removed/changed entries', ['temporal/queries'], 'low', 'low', 'Cross-dimension temporal diff as a first-class query', 'tests/intelligence/temporal.test.ts', 'none', '4.0', 'P1', 'IMPLEMENTED'),
  E('T07', 'Trace(Entity) lifetime queries', 'temporal', 'Element history required manual event filtering', 'trace_element existed but no entity-identity join', 'Roadmap §14 Trace(Entity)', 'Every entity must be queryable through its full lifetime', 'TemporalEngine.traceEntity + IdentityEngine.trail with version history', ['temporal/queries', 'kernel/identity'], 'low', 'low', 'One-call entity lifetime retrieval', 'tests/intelligence/temporal.test.ts', 'none', '4.0', 'P1', 'IMPLEMENTED'),
  E('T08', 'Join(Signals) temporal clusters', 'temporal', 'get_events_around returned flat dumps', 'No multi-signal clustering with entity scoping', 'Roadmap temporal join; Chrome DevTools MCP correlation requests', 'Causal analysis needs joined multi-signal windows, not flat lists', 'Cluster events from multiple sources within withinMs, optionally around an entity', ['temporal/queries'], 'medium', 'low', 'Causal clusters as unit of analysis; span+size metrics', 'tests/intelligence/temporal.test.ts (join + entity scoping)', 'none', '4.0', 'P1', 'IMPLEMENTED'),
  E('T09', 'FirstChange / LastStable predicates', 'temporal', 'No first-meaningful-change or stability-point queries', 'Only manual timestamp arithmetic', 'Roadmap §14 FirstChange/LastStable', '"When did it first go wrong / when was it last healthy" are core debugging questions', 'Predicate-driven firstChange; settleMs-quiet lastStable per dimension', ['temporal/queries'], 'low', 'low', 'Direct answers to first-fault / last-healthy questions', 'tests/intelligence/temporal.test.ts', 'none', '4.0', 'P1', 'IMPLEMENTED'),
  E('T10', 'Branchable timeline (append-only reality)', 'temporal', 'No what-if branching; any mutation risked evidence', 'No branch concept existed', 'Roadmap §17; Replay.io runtime branching is closed-source', 'Counterfactual reasoning requires forking WITHOUT destroying originals', 'BranchManager.fork(): parent + mutation set + deterministic replay; original stream untouched (tested)', ['temporal/branching'], 'high', 'high', 'Safe counterfactual experimentation over recorded history', 'tests/intelligence/temporal.test.ts (branch + original-untouched)', 'branch simulation latency benchmark', '6.0', 'P1', 'IMPLEMENTED', 'branch benchmark'),
  E('T11', 'Causal-descendant suppression propagation', 'temporal', 'Suppressing one event did not remove its causal dependents in replay', 'No causal parent links existed between events', 'Deterministic replay semantics (Replay.io model)', 'Removing a cause must remove effects that would never have happened', 'Fixpoint expansion of suppressed set over causalParentIds in branch replay', ['temporal/branching'], 'medium', 'medium', 'Counterfactuals model true causal dependency, enabling verification', 'tests/intelligence/evidence-causality.test.ts', 'none', '6.0', 'P0', 'IMPLEMENTED'),
  E('T12', 'Indexed tiered event store (hot/warm/cold)', 'temporal', 'Sessions stored as one giant unindexed blob', 'FileStorageProvider JSON blob per session', 'Playwright MCP long-session memory growth; roadmap §41', '10K→10M event sessions need bounded memory + fast indexed access', 'IndexedEventStore: bounded hot ring + warm chunks + cold spool; time/entity/source/type/causal indexes', ['temporal/event-store'], 'high', 'medium', '100K+ events with bounded hot memory; O(log n) time index; entity trace queries', 'tests/intelligence/temporal.test.ts (100K scale)', 'tiering + query latency benchmarks', '4.0', 'P0', 'IMPLEMENTED', '100K store test'),

  // ---- Evidence & causality (13-24) ----
  E('C01', 'Typed evidence graph with provenance edges', 'evidence', 'Events were a timeline, not a graph; no typed relations', 'No node/edge model; correlation was ad-hoc', 'Roadmap §15; DevTools MCP lacks any evidence model', 'Causal browser reasoning requires a typed graph substrate', 'EvidenceGraph: 29 node types × 15 edge types, content-addressed dedup, edges carry provenance + confidence', ['evidence/graph'], 'high', 'medium', 'The causal world model: queryable neighbors/paths with provenance', 'tests/intelligence/evidence-causality.test.ts', 'graph query latency benchmark', '4.0', 'P0', 'IMPLEMENTED'),
  E('C02', 'Corroboration-strengthening edge confidence', 'evidence', 'Repeated observations created duplicate edges', 'No corroboration concept', 'Evidence theory: independent corroboration raises confidence', 'Multiple independent provenances must strengthen the same claim', 'Edge dedup key (from,to,type); repeated addEdge raises confidence +0.05 bounded at 1.0', ['evidence/graph'], 'low', 'low', 'No duplicate edges; corroboration is measurable', 'tests/intelligence/evidence-causality.test.ts', 'none', '4.0', 'P2', 'IMPLEMENTED'),
  E('C03', 'Provenance-derived confidence assessment', 'evidence', 'Confidence numbers were marketing', 'Confidence labels appeared without derivation', 'Roadmap §16 (evidence strength); P1 evidence-before-claims', 'Claims must expose HOW confidence was computed', 'assessConfidence(): weighted source quality × corroboration × verification bonus − counterevidence × kernel multiplier', ['evidence/confidence'], 'medium', 'low', 'Auditable confidence with rationale for every assessment', 'tests/intelligence/evidence-causality.test.ts (5 confidence tests)', 'none', '4.0', 'P0', 'IMPLEMENTED'),
  E('C04', 'Correlation ≠ causation classification', 'causality', 'Precedence was implicitly treated as causation', 'Correlators labeled chains without explicit classification', 'Roadmap §16; scientific method; false-success reports in agent tools', 'A→B timing must never silently become "A caused B"', 'Every causal link carries OBSERVED/CORRELATED/SUPPORTED/... classification + alternatives + verification method', ['causality/engine'], 'medium', 'medium', 'Structural honesty in every causal claim', 'tests/intelligence/evidence-causality.test.ts (classification test)', 'none', '5.0', 'P0', 'IMPLEMENTED'),
  E('C05', 'Rule-pair causal inference map (O(1) lookup)', 'causality', 'Causal rules scanned per pair (O(rules) per pair)', 'No causal rule engine at all', 'Chrome DevTools MCP correlation; rrweb has no causality', 'Correlation over 2000-event windows must be fast (39s → 150ms measured)', 'Precomputed source-pair rule map + bounded link cap (20K) with deterministic truncation', ['causality/engine'], 'medium', 'low', '260x faster investigation latency (measured 39790ms → 148ms at 10K scale)', 'tests/intelligence/registry-integration.test.ts', 'investigation latency benchmark', '5.0', 'P1', 'IMPLEMENTED', 'investigation latency'),
  E('C06', 'Root-cause chain reconstruction', 'causality', 'Root cause was a guess from error text', 'fx_error_root_cause heuristics without chain evidence', 'Roadmap §8 causal chain', 'The full user→network→state→render→removal chain must be reconstructable', 'Backward walk from symptom through strongest links, depth-bounded, with evidence refs per link', ['causality/engine'], 'high', 'medium', 'Explainable root-cause chains with per-link evidence', 'tests/intelligence/evidence-causality.test.ts (chain test)', 'none', '5.0', 'P0', 'IMPLEMENTED'),
  E('C07', 'Hypothesis generation + depth-rewarded ranking', 'causality', 'Single-answer root cause without alternatives', 'No competing hypotheses', 'Differential diagnosis model; roadmap hypothesis ranking', 'Debugging needs ranked alternatives, not one guess', 'Chains seeded per candidate; confidence × depth reward (deeper root = more complete explanation); explicit rank + status', ['causality/engine'], 'medium', 'medium', 'Ranked competing root-cause hypotheses with verification methods', 'tests/intelligence/evidence-causality.test.ts + golden suite', 'root-cause accuracy 100% on golden suite', '5.0', 'P1', 'IMPLEMENTED', 'rootCauseAccuracy'),
  E('C08', 'Counterfactual suppression engine', 'causality', 'No what-if verification of causes', 'None', 'Roadmap counterfactual engine; category-creating capability', '"Remove the cause — does the symptom vanish?" must be answerable', 'CounterfactualEngine.run(): fork + suppress + compare + verdict CAUSE_SUPPPORTED/NOT_SUPPORTED/INCONCLUSIVE with confidence', ['simulation/counterfactual', 'temporal/branching'], 'high', 'high', 'What-if debugging; the differentiating v6 capability', 'tests/intelligence/evidence-causality.test.ts (3 counterfactual tests)', 'none', '6.0', 'P0', 'IMPLEMENTED'),
  E('C09', 'Replay-fidelity gating of verdicts', 'causality', 'Visual/performance diffs were treated as causal proof', 'Visual regression tooling claimed causation', 'Roadmap §42 (fidelity levels); "screenshot diff alone is not causal proof"', 'Suppression can only prove causation for deterministic-replay dimensions', 'symptomFidelity(): dom/runtime/network/performance = deterministic; visual + accumulation patterns (memory/leak/growth) = partial → INCONCLUSIVE', ['simulation/counterfactual'], 'medium', 'medium', 'Zero false-success verdicts on partial-fidelity symptoms (golden suite 0.00%)', 'tests/intelligence golden suite (false success 0.00%)', 'falseSuccessRate metric', '6.0', 'P0', 'IMPLEMENTED', 'falseSuccessRate=0'),
  E('C10', 'Earliest-divergence breakpoint analysis', 'causality', 'No way to locate where two timelines split', 'None', 'Roadmap breakpoint concept; bisect-style debugging', 'Branch comparison must point at the FIRST differing event', 'CausalEngine.earliestDivergence(reality, branch) → first sequence missing from branch', ['causality/engine'], 'low', 'low', 'Bisect-style temporal debugging', 'tests/intelligence/evidence-causality.test.ts', 'none', '5.0', 'P2', 'IMPLEMENTED'),
  E('C11', 'Blast-radius impact estimation', 'causality', 'Impact of a cause was unmeasured', 'None', 'Roadmap §68 blast radius question', 'Agents must know direct vs second-order effects before acting', 'causeImpact(): direct + second-order causal children + affected-entity count', ['v12/mcp handler'], 'low', 'low', 'Blast radius answers for every candidate cause', 'tests/intelligence registry smoke', 'none', '5.0', 'P2', 'IMPLEMENTED'),
  E('C12', 'Bounded causal graph budgets', 'causality', 'Graph growth unbounded on hostile pages', 'No MAX_GRAPH_NODES enforcement', 'Roadmap §26 budgets; mutation-storm resilience', 'A mutation storm must not OOM the graph', 'EvidenceGraph(maxNodes): overflow observations get identity nodes without storage; degraded flag exposed to health', ['evidence/graph'], 'low', 'medium', 'Graph memory strictly bounded; degradation observable', 'tests/intelligence/evidence-causality.test.ts (bounded graph test)', 'none', '8.0', 'P0', 'IMPLEMENTED'),

  // ---- Identity & semantics (25-34) ----
  E('S01', 'Persistent entity identity with version history', 'identity', 'LogicalNodeId died with DOM representation changes', 'Node identity broke on rerender/reparent', 'Roadmap §6 identity engine; P4 identity-survival principle', 'The same logical entity must survive rerenders, reparenting and navigation', 'IdentityEngine: durable ids + fingerprint rematching + version trail + owner/parent links', ['kernel/identity'], 'high', 'medium', 'Entities trackable across representation churn; honest no-match refusals', 'tests/intelligence/kernel.test.ts (identity tests)', 'none', '4.0', 'P0', 'IMPLEMENTED'),
  E('S02', 'Semantic DOM layer (roles, purpose, state, stability)', 'semantic', 'Raw DOM is noise for agents', 'Class soup like "x7 a91" was all an agent saw', 'Playwright a11y-tree snapshots; roadmap semantic DOM', 'Agents need meaning, not markup', 'SemanticEngine.semanticDom(): role by tag/aria/testid, purpose strings, states, stability scoring from anchor signals, selector candidates', ['semantics/semantic-engine'], 'medium', 'low', 'Token-efficient, meaning-bearing page model', 'tests/intelligence/security-resilience.test.ts (semantic tests)', 'context tokens metric', '5.0', 'P1', 'IMPLEMENTED'),
  E('S03', 'Component boundary inference (React/Vue/Svelte/custom/iframe)', 'component', 'Component boundaries were invisible', 'fx_component_boundaries had partial coverage without lifecycle', 'Roadmap component intelligence', 'Component-level causality requires boundary detection', 'Fingerprint-based framework detection with evidence + confidence; component ids + ownership', ['semantics/semantic-engine'], 'medium', 'low', 'Component-scoped analysis and ownership', 'tests/intelligence/security-resilience.test.ts', 'none', '5.0', 'P1', 'IMPLEMENTED'),
  E('S04', 'Component lifecycle derivation (mount/update/remount/unmount)', 'component', 'No mount/unmount tracking for components', 'None', 'React/Vue remount debugging folklore', '"Which component remounted and when" is a top SPA debugging question', 'lifecycleFromEvents(): mount/update/remount/unmount with event evidence', ['semantics/semantic-engine'], 'medium', 'low', 'Component time machine', 'tests/intelligence/security-resilience.test.ts (lifecycle test)', 'none', '5.0', 'P1', 'IMPLEMENTED'),
  E('S05', 'Multi-signal target resolution engine', 'targeting', 'Selectors were the only targeting signal', 'generate_element_target ranked selectors only', 'Playwright ref/uid model; roadmap target intelligence', 'Natural-language + semantic targeting must beat selector guessing', 'TargetIntelligence.resolve(): structural/semantic/historical/behavioral/visual signals with weights, evidence and honest statuses', ['targeting/target-intelligence'], 'high', 'medium', 'Intent-level targeting with confidence + verification', 'tests/intelligence/security-resilience.test.ts (targeting tests)', 'none', '5.0', 'P1', 'IMPLEMENTED'),
  E('S06', 'Ambiguity refusal (no blind clicking)', 'targeting', 'Nearest-match could be silently wrong', 'Recovery below 0.62 refused but resolution did not', 'Browser Use false-success reports; roadmap "never blindly click"', 'Two similar candidates must surface AMBIGUOUS, not a guess', 'Resolution returns AMBIGUOUS with warnings when top-2 within 0.08', ['targeting/target-intelligence'], 'low', 'medium', 'No silent wrong-target actions', 'tests ambiguous twins test', 'none', '5.0', 'P0', 'IMPLEMENTED'),
  E('S07', 'Multi-signal target recovery after rerender', 'targeting', 'Selector recovery used fingerprint matching only', 'recover_selector single strategy', 'Self-healing selectors ecosystem (e.g. Healenium); roadmap recovery', 'Targets must survive rerender/remount/SPA navigation without agent retries', 'recover(): semantic id + text + role + component + ancestry scoring; refuses below 0.5 as blind guess', ['targeting/target-intelligence'], 'medium', 'medium', 'Self-healing targeting with honest refusals', 'tests recovery test', 'none', '5.0', 'P1', 'IMPLEMENTED'),
  E('S08', 'Durable target contracts', 'targeting', 'Targets were re-resolved from scratch each time', 'None', 'Roadmap target contracts', 'Repeated interactions should reuse verified resolutions', 'Contract registry keyed by query+semantic id with selector fallbacks + reuse counts', ['targeting/target-intelligence'], 'low', 'low', 'Stable cross-call target identity', 'tests contract test', 'none', '5.0', 'P2', 'IMPLEMENTED'),
  E('S09', 'Accessibility-first semantic signals', 'a11y', 'A11y was a side tool, not a targeting signal', 'get_element_accessibility existed as inspection', 'Playwright a11y snapshot philosophy; roadmap §45', 'Roles/names/labels are the most stable targeting anchors', 'A11y fields integrated into semantic model + accessibility model tool', ['semantics/semantic-engine'], 'low', 'low', 'Stable targeting + a11y visibility in one model', 'tests a11y model test', 'none', '5.0', 'P2', 'IMPLEMENTED'),
  E('S10', 'Page-intent workflow inference', 'semantic', 'Page purpose required full DOM dumps', 'None', 'Roadmap page intent', 'Agents need interaction zones without full state', 'Workflow/zone inference from semantic roles + interactive elements', ['v12/mcp handler'], 'low', 'low', 'L1-level page understanding', 'tests page intent smoke', 'context tokens metric', '5.0', 'P3', 'IMPLEMENTED'),

  // ---- Simulation & verification (35-46) ----
  E('V01', 'Verification contracts (mustHold/mustNotHold/evidence)', 'verification', 'Action success was reported without postcondition checks', 'Tools returned success on action completion', 'Browser Use false-success issue class; roadmap §19/P10', 'Action ≠ success; postconditions must be checked with required evidence', 'VerificationContract with mustHold/mustNotHold/timeWindow/evidenceRequired → PASS/FAIL/INCONCLUSIVE', ['verification/proof'], 'medium', 'medium', 'No synthetic success: missing evidence → INCONCLUSIVE (tested)', 'tests/intelligence/evidence-causality.test.ts (4 verification tests)', 'falseSuccessRate 0.00%', '4.0', 'P0', 'IMPLEMENTED', 'falseSuccess metric'),
  E('V02', 'Machine-verifiable proof records', 'proof', 'No proof artifacts for conclusions', 'None', 'Roadmap proof engine; forensic evidence standards', 'Resolved incidents must be independently checkable', 'ProofRecord: claims + steps + evidence refs + content hash + previous-proof chaining; verifyProof() re-computes hash', ['verification/proof'], 'medium', 'low', 'Tamper-evident, independently re-checkable conclusions', 'tests proof tamper test', 'none', '12.0', 'P0', 'IMPLEMENTED'),
  E('V03', 'Safe mutation transactions (10-phase pipeline)', 'mutation', 'DOM mutations were direct with best-effort undo', 'mutate_dom_transaction existed without risk/simulation phases', 'Roadmap §18; database transaction discipline', 'Mutations need PLAN→SCOPE→RISK→PRE→SIM→APPLY→OBSERVE→POST→VERIFY→COMMIT/ROLLBACK', 'SafeMutationEngine with adapter choke point, audit trail, rollback unless unsafe', ['mutation/transaction'], 'high', 'high', 'Transactional mutations with scope rejection, destructive gating, rollback', 'tests/intelligence/incident-investigation.test.ts (4 mutation tests)', 'none', '6.0', 'P0', 'IMPLEMENTED'),
  E('V04', 'Destructive-action classification + default-off', 'mutation', 'remove-node/eval were undifferentiated from set-attribute', 'No risk classes', 'OWASP-safe tooling; roadmap destructive classification', 'High-risk operations must be gated by policy, not hope', 'Risk levels LOW/MEDIUM/HIGH/DESTRUCTIVE; DESTRUCTIVE + HIGH blocked unless explicitly allowed', ['mutation/transaction'], 'low', 'high', 'Dangerous mutations impossible by accident', 'tests destructive-blocked test', 'policy gate', '6.0', 'P0', 'IMPLEMENTED'),
  E('V05', 'Prediction engine with mandatory epistemics', 'prediction', 'No prediction capability', 'None', 'Roadmap prediction; forecasting discipline', 'Predictions must expose confidence/assumptions/counterevidence/horizon/verification path', 'Pattern-triggered predictions (failure-risk, resource-risk, state-transition) with full epistemic payload', ['simulation/predictor'], 'medium', 'medium', 'Forward-looking intelligence that never poses guesses as facts', 'tests prediction tests', 'none', '6.0', 'P2', 'IMPLEMENTED'),
  E('V06', 'INCONCLUSIVE-never-PASS discipline', 'verification', 'Ambiguous outcomes were silently successful', 'Error swallowing paths in tool handlers', 'Priority 3 no-fake-success', 'The single most dangerous failure mode in agent tooling', 'Status taxonomy PASS/FAIL/INCONCLUSIVE/UNSUPPORTED/DEGRADED/PARTIAL enforced across all 100 td_* tools (smoke-tested)', ['v12/mcp handler'], 'low', 'medium', 'Honest statuses everywhere; 0.00% false success measured', 'tests/intelligence registry smoke (status taxonomy)', 'falseSuccessRate', '4.0', 'P0', 'IMPLEMENTED', 'smoke matrix'),
  E('V07', 'Throwing-check containment in verification', 'verification', 'A throwing postcondition crashed verification', 'None', 'Defensive verification', 'Broken checks must FAIL, not crash', 'safeCheck() wraps all postcondition checks', ['verification/proof'], 'low', 'low', 'Robust verification under broken predicates', 'tests throwing-check test', 'none', '4.0', 'P2', 'IMPLEMENTED'),
  E('V08', 'Incident lifecycle state machine', 'incident', 'Sessions had no incident concept', 'Session-centric model', 'Roadmap §21 incident lifecycle; ITSM practice', 'Bugs need explicit lifecycles with valid transitions', '13-state machine (CREATED→…→RESOLVED/ABANDONED) with VALID_TRANSITIONS + audit trail', ['incident/model'], 'medium', 'low', 'Enforced, auditable incident progression', 'tests lifecycle tests (valid+invalid)', 'none', '7.0', 'P1', 'IMPLEMENTED'),
  E('V09', 'Portable .tdom forensic artifacts', 'incident', 'Session export was JSON blob', 'export_session JSON', 'Roadmap §22; evidence portability', 'Incidents must be transportable, reviewable, machine-ingestible', 'TdomFormat: versioned manifest, content-addressed sections, gzip, compatibility info; tamper detection on import', ['incident/format'], 'high', 'medium', 'Round-trip verified, tamper-evident incident packages', 'tests/intelligence .tdom tests (round-trip, gzip, tamper)', 'export throughput', '7.0', 'P1', 'IMPLEMENTED'),
  E('V10', 'Tamper detection on artifact import', 'incident', 'Imported sessions were trusted', 'No verification on import', 'Forensic chain of custody', 'Modified artifacts must be detected, never silently accepted', 'Per-section hash + manifest hash re-verification; brokenSection reported', ['incident/format'], 'medium', 'low', 'Imported evidence integrity is provable', 'tests tamper test', 'none', '7.0', 'P0', 'IMPLEMENTED'),
  E('V11', 'Resumable investigation plans', 'incident', 'Investigations were manual tool-call sequences with no state', 'None', 'Roadmap §20 resumable plans; agent goal-retention complaints', 'Interrupted investigations must continue, not restart', 'InvestigationPlan with per-step status + completedThrough + resumePlanId support', ['incident/investigation'], 'medium', 'medium', 'Durable, resumable autonomous investigations', 'tests resumable-plan test', 'none', '7.0', 'P1', 'IMPLEMENTED'),
  E('V12', 'Autonomous investigator (td_investigate)', 'incident', 'Agent manually orchestrated 30+ tool calls', 'prompts hinted at workflows', 'Roadmap §20; unified diagnostic bundle requests', 'A natural-language objective must become a full investigation', '13-step orchestrated plan: scope→incident→baseline→observe→timeline→reconstruct→correlate→graph→hypotheses→counterfactual→verify→proof→lesson', ['incident/investigation'], 'high', 'high', 'The flagship: objective in, verified root cause + proof out', 'tests/intelligence §78 end-to-end test', 'investigation latency benchmark', '7.0', 'P0', 'IMPLEMENTED', 'ICR=100%'),

  // ---- Security (47-58) ----
  E('X01', 'Zero-trust page model', 'security', 'Page content could implicitly flow into agent context', 'No trust separation', 'Prompt-injection literature; roadmap §23', 'Page text is untrusted data and must never become policy', 'ZeroTrustModel: origin trust, instruction-source tagging, page-content quarantine', ['security/zero-trust'], 'high', 'high', 'Structural injection defense', 'tests zero-trust tests', 'architecture-level', '9.0', 'P0', 'IMPLEMENTED'),
  E('X02', 'Prompt-injection pattern detection', 'security', 'No injection detection', 'None', 'OWASP LLM Top-10; injection attack patterns', 'Instruction-override/role-hijack/policy-exfiltration attempts must be flagged', '7 pattern families with multi-pattern confidence + evidence refs', ['security/zero-trust'], 'low', 'medium', 'Detected + quarantined injection attempts with evidence', 'tests injection tests', 'none', '9.0', 'P0', 'IMPLEMENTED'),
  E('X03', 'Secret detection + redaction with human-only reveal', 'security', 'Privacy engine masked known patterns; reveal rules unclear', 'RedactionEngine existed for storage', 'Roadmap §22 privacy; secret-exposure defense', 'Secrets must be redacted before agent eyes; unmasking is human-only + audited', '8 secret families; agent reveal attempts BLOCKED and audited; human reveal ALLOWED and audited', ['security/zero-trust'], 'medium', 'high', 'Verifiable redaction + dual-audit trail', 'tests redaction/reveal test', 'redaction audit', '9.0', 'P0', 'IMPLEMENTED'),
  E('X04', 'Exfiltration detection', 'security', 'Secret-bearing outbound payloads undetected', 'None', 'Client-side security monitoring; OWASP', 'Credentials flowing to unexpected origins must be caught', 'detectExfiltration(): destination origin + payload-kind classification + quarantine audit', ['security/zero-trust'], 'medium', 'medium', 'Outbound secret leakage observability', 'tests exfiltration test', 'none', '9.0', 'P1', 'IMPLEMENTED'),
  E('X05', 'Passive security posture suite', 'security', 'No browser-side security analyzers', 'None', 'OWASP ZAP browser-resident trend; roadmap §24', 'Client-visible security signals complement proxy-side scanning', '10 analyzers: dom-xss source/sink, CSP, cookies, storage, iframes, postMessage, third-party, mixed-content, auth, secret-exposure', ['security/analyzers'], 'high', 'medium', 'Evidence-driven browser security posture with findings model', 'tests security analyzer tests', 'none', '9.0', 'P1', 'IMPLEMENTED'),
  E('X06', 'Findings verification status discipline', 'security', 'Scanners report suspicion as vulnerability', 'Common DAST noise problem', 'Roadmap findings model; false-positive fatigue', 'Suspicion must never be CONFIRMED without reproduction', 'Finding statuses CONFIRMED/PROBABLE/POTENTIAL/BENIGN/NOT_REPRODUCIBLE enforced by test', ['security/analyzers'], 'low', 'medium', 'Signal-to-noise preserved; agents cannot treat hypotheses as facts', 'tests never-CONFIRMED-without-repro test', 'none', '9.0', 'P0', 'IMPLEMENTED'),
  E('X07', 'Active-testing policy gates', 'security', 'Active testing could silently escalate from passive', 'No scope/rate/budget controls', 'Roadmap §25; authorized-testing standards', 'Passive analysis must never become active exploitation silently', 'ActiveTestGate: mode, origin allowlist, category allowlist, rate limit, request budget, destructive default-off, kill switch', ['security/analyzers'], 'medium', 'high', 'All five gate dimensions tested and enforced', 'tests gate tests (5 tests)', 'none', '9.0', 'P0', 'IMPLEMENTED'),
  E('X08', 'Kill switch for all active security testing', 'security', 'Active security testing had no emergency stop mechanism once authorized', 'No way to instantly halt authorized active testing', 'Range-safety engineering practice (hardware/software test ranges require a big red button)', 'An authorized active test that misbehaves must be stoppable instantly, before budget/rate limits catch it', 'engageKillSwitch() flips a policy flag that every authorization check consults first; all subsequent active-test requests are refused with an explicit kill-switch reason', ['security/analyzers', 'v12/mcp handler'], 'low', 'low', 'One-call emergency containment of all active testing', 'tests kill-switch test (gate refuses after engage)', 'none', '9.0', 'P0', 'IMPLEMENTED'),
  E('X09', 'DOM XSS longest-source matching', 'security', 'Source attribution matched bare "location" over "location.hash"', 'Initial implementation ambiguity', 'Source/sink analysis precision', 'XSS findings must cite the precise source', 'Longest-match source selection in domXssAudit', ['security/analyzers'], 'low', 'low', 'Precise source attribution in findings', 'tests XSS source test', 'none', '9.0', 'P2', 'IMPLEMENTED'),
  E('X10', 'Cross-origin secret-exposure findings', 'security', 'Credential destinations were not compared to page origin', 'None', 'CORS trust expectations; roadmap', 'Authorization headers to cross-origin endpoints are high-signal findings', 'secretExposureAudit with page-origin comparison', ['security/analyzers'], 'low', 'medium', 'High-severity exposure findings with data flow', 'tests exposure test', 'none', '9.0', 'P1', 'IMPLEMENTED'),

  // ---- Reliability & resources (59-70) ----
  E('R01', 'Self-healing runtime state machine', 'resilience', 'Bridge failures required manual restart', 'Bridge health existed but no state machine', 'Chrome DevTools MCP crash-recovery issues; roadmap §27', 'CONNECTED→DEGRADED→DISCONNECTED→RECOVERING→REATTACHED→RECONCILED with evidence preservation', 'SelfHealingRuntime with snapshot-before-recovery, bounded attempts (3), exponential backoff', ['resilience/guardian'], 'high', 'medium', 'Recovery is a modeled, observable transition', 'tests recovery tests', 'recovery time benchmark', '8.0', 'P0', 'IMPLEMENTED', 'recovery benchmark'),
  E('R02', 'Bounded recovery (no infinite retries)', 'resilience', 'Reconnect loops could spin forever', 'Unbounded retry risk', 'Roadmap "no infinite retry loop"', 'Retry storms are self-inflicted DoS', 'maxAttemptsPerFailure=3 with reason-aware outcomes; FAILED result after exhaustion', ['resilience/guardian'], 'low', 'medium', 'Guaranteed retry termination', 'tests never-loops test', 'none', '8.0', 'P0', 'IMPLEMENTED'),
  E('R03', 'Evidence-preserving recovery snapshots', 'resilience', 'Crashes lost session state', 'None', 'Crash-recovery requirements', 'Incidents/identity/evidence/checkpoints/head-sequence must survive failures', 'RecoverySnapshot captured BEFORE recovery attempts; preserved list reported per attempt', ['resilience/guardian'], 'medium', 'medium', 'Post-crash state continuity with proof', 'tests preservation test', 'none', '8.0', 'P0', 'IMPLEMENTED'),
  E('R04', 'Resource guardian with budgets', 'resilience', 'No resource budget enforcement', 'None', 'Playwright MCP memory growth; roadmap §28 budgets', 'TeleDOM must never become the performance problem', 'Guardian: events/bytes/memory/graph/network/queue budgets → pressure ratio', ['resilience/guardian'], 'medium', 'medium', 'Utilization-aware capture policy', 'tests guardian test', 'none', '8.0', 'P0', 'IMPLEMENTED'),
  E('R05', 'Adaptive degradation modes', 'resilience', 'No graceful degradation — either full capture or crash', 'None', 'Roadmap healthy→emergency ladder', 'Pressure must degrade fidelity, not kill the session', 'HEALTHY/FULL_FIDELITY → PRESSURED/COMPACT → CRITICAL/SAMPLING → EMERGENCY/PRESERVE_EVIDENCE+CHECKPOINT+RECOVER', ['resilience/guardian'], 'low', 'medium', 'Bounded, ladder-style degradation (tested at all 4 levels)', 'tests degradation test', 'none', '8.0', 'P0', 'IMPLEMENTED'),
  E('R06', 'Session repair from serialized stream', 'resilience', 'Partially corrupted sessions were unusable', 'None', 'Roadmap session repair', 'Interrupted storage must be repairable from checkpoints + evidence', 'serialize() → fresh mesh restore() with chain re-verification; td_session_repair tool', ['kernel/events', 'v12/mcp handler'], 'medium', 'medium', 'Hash-verified session resurrection', 'tests session-repair dispatch + chaos storage-interruption', 'recovery time benchmark', '8.0', 'P1', 'IMPLEMENTED', 'recovery benchmark'),
  E('R07', 'Chaos engineering suite (16 injections)', 'resilience', 'No failure-injection testing', 'None', 'Chaos engineering practice; roadmap §39', 'Failure must be contained/observed/explained/recoverable — not "never happens"', 'injectChaos(): crash/disconnect/reload/duplication/reorder/delay/loss/corruption/storm/pressure + containment verification', ['chaos/chaos.ts'], 'high', 'medium', '16/16 injections contained+observed+explained+recoverable', 'tests chaos test', 'chaos metrics in BENCHMARKS.md', '11.0', 'P0', 'IMPLEMENTED', '16/16 contained'),
  E('R08', 'Corruption rejection (never merge bad evidence)', 'resilience', 'Corrupted input silently merged', 'None', 'Byzantine-input defense', 'Tampered envelopes must be rejected before they poison the chain', 'Integrity-hash verification on append; REJECTED_CORRUPT status; counted in stats', ['kernel/events'], 'low', 'high', 'Corrupt events can never enter the evidence chain', 'tests corruption test + chaos artifact-corruption', 'none', '8.0', 'P0', 'IMPLEMENTED'),
  E('R09', 'Mutation-storm containment', 'resilience', 'Storms could exhaust memory', 'None', 'Hostile-page resilience; roadmap §26', '3000-event storms must be admitted with valid chain', 'Chaos mutation-storm injection verifies chain validity after storm', ['chaos/chaos.ts'], 'low', 'medium', 'Storm-proof kernel', 'tests chaos storm', 'none', '8.0', 'P1', 'IMPLEMENTED'),
  E('R10', 'Kernel self-diagnostics', 'resilience', 'TeleDOM could not assess its own health', 'recording_health was partial', 'Roadmap §35 self-diagnosis', '"I may be producing invalid evidence" must be detectable and confidence-damping', 'KernelDiagnostics: 6 probes (event/storage integrity, guardian, runtime, graph, security) → confidenceMultiplier', ['kernel/lifecycle', 'platform'], 'medium', 'medium', 'Health-gated confidence — degradation lowers downstream confidence', 'tests health snapshot test', 'none', '8.0', 'P0', 'IMPLEMENTED'),
  E('R11', 'Degraded-confidence propagation', 'resilience', 'Unhealthy kernel still produced full-confidence claims', 'None', 'Epistemic honesty under failure', 'System uncertainty must reduce claim confidence', 'health().confidenceMultiplier wired into assessConfidence', ['evidence/confidence', 'platform'], 'low', 'medium', 'Uncertainty propagates honestly', 'tests confidence multiplier test', 'none', '8.0', 'P1', 'IMPLEMENTED'),
  E('R12', 'Runtime crash family exercises', 'resilience', 'page/renderer/browser/bridge crashes were untested paths', 'None', 'Crash matrices in MCP issue trackers', 'Every crash kind must be a modeled transition', 'td_recover_browser/page/bridge + chaos page/renderer/browser injections', ['resilience/guardian', 'chaos'], 'low', 'low', 'Crash recovery exercised per kind', 'tests recovery dispatch + chaos', 'none', '8.0', 'P2', 'IMPLEMENTED'),

  // ---- Agent OS & context (71-80) ----
  E('A01', 'Capability registry as single source of truth', 'agent-os', 'Tool counts/versions drifted across files (121/43/206 mismatch)', 'Manual duplication in README/entrypoints/definitions', 'Doc-drift was a baseline defect; roadmap §31', 'Version, tool count, schema, docs, tests must generate from ONE registry', 'CAPABILITY_REGISTRY: 100 td_* capabilities with full metadata; MCP defs/docs/compat generated from it', ['registry/capabilities', 'registry/td-tools'], 'medium', 'medium', 'Structurally impossible drift for the td_* surface', 'tests registry generation test', 'none', '10.0', 'P0', 'IMPLEMENTED'),
  E('A02', 'Intent-level tool architecture (100 td_* facades)', 'agent-os', '206 flat tools forced manual agent orchestration', 'Tool-per-command model', 'Roadmap §30; token-cost complaints', 'Agents should express intent; the platform orchestrates', 'td_* families compose kernel/temporal/evidence/causal primitives via one dispatcher — not 100 isolated handlers', ['v12/mcp handler'], 'high', 'medium', 'Investigation-level calls replace 30-call sequences', 'tests smoke matrix', 'tool_calls_to_decision metric', '10.0', 'P0', 'IMPLEMENTED'),
  E('A03', 'L0-L4 context levels', 'agent-os', 'Full snapshots flooded context windows', '500KB state dumps', 'Playwright MCP context overload; roadmap §29', 'The agent should receive minimal sufficient context', 'ContextPlanner: L0 identity → L1 semantic → L2 subtree → L3 evidence → L4 full; artifacts externalized', ['agent/context'], 'high', 'medium', 'Measured: L1 ≈ 1.5K tokens vs 125K full-state tokens', 'tests context planner tests', 'agent-context tokens metric', '10.0', 'P0', 'IMPLEMENTED', 'token reduction'),
  E('A04', 'Duplicate suppression + novelty in context', 'agent-os', 'Repeated semantic entries wasted tokens', 'None', 'Context economics', 'Same-role elements are redundant', 'Deterministic dedup on role+text with suppression notes', ['agent/context'], 'low', 'low', 'Fewer tokens per decision', 'tests dedup test', 'bytes_to_decision', '10.0', 'P2', 'IMPLEMENTED'),
  E('A05', 'Context economics metrics', 'agent-os', 'Token cost of decisions was unmeasured', 'None', 'Roadmap context tracking', 'bytes/tokens/tool-calls/failed-actions per decision are first-class metrics', 'ContextMetrics accumulated per plan() call', ['agent/context'], 'low', 'low', 'Quantified context efficiency', 'tests metrics assertions', 'token metric', '10.0', 'P1', 'IMPLEMENTED'),
  E('A06', 'Durable agent memory with provenance', 'agent-os', 'No cross-session knowledge', 'None', 'Roadmap §33 agent memory', 'Learned facts (components, failures, fixes, invariants) must persist with confidence', 'AgentMemory: 12 memory kinds, provenance per item, validation feedback loops', ['agent/memory'], 'medium', 'medium', 'Knowledge compounding across investigations', 'tests memory tests', 'none', '10.0', 'P1', 'IMPLEMENTED'),
  E('A07', 'Uncertainty-gated memory (no fact inflation)', 'agent-os', 'Memory would treat hunches as facts', 'None', 'Roadmap "do not treat uncertain memory as fact"', 'Low-confidence memories must be flagged unvalidated', 'validated flag (confidence ≥ 0.75); query onlyValidated filters', ['agent/memory'], 'low', 'medium', 'Facts vs hypotheses structurally separated', 'tests memory validation tests', 'none', '10.0', 'P0', 'IMPLEMENTED'),
  E('A08', 'Learning limited to heuristic boosts', 'agent-os', 'Learning could silently alter policy/code', 'None', 'Roadmap §34 no unsafe self-modification', 'Observation must never become unauthorized change', 'heuristicBoost() only influences ranking scores (bounded ≤ 0.2); never security policy', ['agent/memory'], 'low', 'high', 'Safe learning boundary', 'tests boost test', 'none', '10.0', 'P0', 'IMPLEMENTED'),
  E('A09', 'Declarative workflow execution with recovery', 'agent-os', 'Multi-step agent flows had no recovery semantics', 'None', 'Roadmap run_workflow', 'Multi-step operations need per-step status + honest PARTIAL results', 'td_run_workflow: executes step tools, collects per-step statuses, PARTIAL when any step degrades', ['v12/mcp handler'], 'medium', 'low', 'Composable agent workflows', 'tests workflow smoke + operational', 'none', '10.0', 'P2', 'IMPLEMENTED'),
  E('A10', 'Playbook library', 'agent-os', 'No reusable investigation procedures', 'None', 'SRE playbook practice', 'Common scenarios should be one call', 'td_run_playbook: disappearing-ui, security-passive, performance-scan, recovery-drill', ['v12/mcp handler'], 'low', 'low', 'Reusable expert procedures', 'tests playbook smoke', 'none', '10.0', 'P3', 'IMPLEMENTED'),

  // ---- Golden/benchmark/testing (81-90) ----
  E('G01', 'Golden incident suite (1000+ deterministic scenarios)', 'testing', 'No ground-truth investigation benchmark', 'None', 'Roadmap §38 golden incidents; benchmark-driven disciplines', 'The engine must be graded against known root causes', 'generateGoldenSuite: 24 categories × seeds = 1032 scenarios with expected root cause/verification; deterministic PRNG', ['golden/generator'], 'high', 'medium', 'ICR/EC/RF/FalseSuccess measured against ground truth', 'tests golden suite test', 'golden metrics', '11.0', 'P0', 'IMPLEMENTED', 'ICR 100%'),
  E('G02', 'Investigation Completion Rate metric', 'testing', 'No completion metric existed', 'None', 'Roadmap-defined ICR', 'Resolved/resolvable is the product quality metric', 'ICR = resolved / resolvable (INCONCLUSIVE-expected scenarios excluded from denominator — honest)', ['golden/generator'], 'low', 'low', 'Product-quality north-star metric', 'tests metric assertions', 'ICR in BENCHMARKS.md', '11.0', 'P0', 'IMPLEMENTED', 'ICR=100%'),
  E('G03', 'Evidence Confidence metric', 'testing', 'No verification-quality metric', 'None', 'Roadmap EC', 'Verified findings / reported findings measures claim quality', 'EC computed per suite run', ['golden/generator'], 'low', 'low', 'Claim-quality tracking', 'tests metric', 'EC in BENCHMARKS.md', '11.0', 'P1', 'IMPLEMENTED', 'EC=83.3%'),
  E('G04', 'Replay Fidelity metric', 'testing', 'No replay-quality metric', 'None', 'Roadmap RF', 'Reproduced/recorded causal outcomes measures counterfactual fidelity', 'RF computed per suite run', ['golden/generator'], 'low', 'low', 'Replay-quality tracking', 'tests metric', 'RF in BENCHMARKS.md', '11.0', 'P1', 'IMPLEMENTED', 'RF=100%'),
  E('G05', 'False Success Rate metric', 'testing', 'False successes were invisible', 'Reported-issue class', 'No-fake-success priority', 'Claimed PASS where INCONCLUSIVE expected must be measured', 'FSR per suite run; 0.00% achieved', ['golden/generator'], 'low', 'high', 'The anti-marketing metric', 'tests metric', 'FSR in BENCHMARKS.md', '11.0', 'P0', 'IMPLEMENTED', 'FSR=0.00%'),
  E('G06', 'Honest scenario denominators', 'testing', 'Metrics could punish honest non-resolution', 'None', 'Metric design discipline', 'INCONCLUSIVE-expected scenarios are not failures', 'resolvable denominator + resolvableScenarios/resolvedScenarios exposed', ['golden/generator'], 'low', 'low', 'Metrics that reward honesty', 'tests metric', 'none', '11.0', 'P2', 'IMPLEMENTED'),
  E('G07', 'Real benchmark matrix (10K/100K/1M)', 'benchmarking', '"Sub-millisecond" was unmeasured marketing', 'No benchmarks', 'Roadmap §37; baseline 5.5/10 benchmark-evidence score', 'Capture/query/reconstruction/recovery latencies must be published', 'runBenchmarks with p50/p95/p99 per scale + docs generated from measurements', ['bench/benchmarks'], 'high', 'low', 'Published, reproducible performance evidence', 'tests suite-reports test', 'BENCHMARKS.md', '11.0', 'P0', 'IMPLEMENTED', 'full matrix'),
  E('G08', 'Resolution/latency separation', 'benchmarking', 'Timestamp resolution was conflated with latency', 'Marketing conflation', 'Roadmap explicit requirement', '0.01ms resolution is a clock property; p99 latency is a compute property', 'Separate columns in benchmark matrix + note', ['bench/benchmarks'], 'low', 'low', 'No misleading performance claims', 'tests resolution assertion', 'benchmark doc', '11.0', 'P0', 'IMPLEMENTED'),
  E('G09', 'Test-generated documentation', 'docs', 'Docs drifted from implementation', '121/43/206 count drift at baseline', 'Doc-drift defect class', 'Docs must be output of passing tests', 'BENCHMARKS.md written by suite-reports test; improvement matrix is a registry validated by test', ['tests/intelligence/suite-reports', 'registry/improvements'], 'low', 'low', 'Docs that cannot lie', 'tests doc-existence assertions', 'none', '11.0', 'P1', 'IMPLEMENTED'),
  E('G10', 'Operational certification extended to 306 tools', 'testing', 'Operational suite covered 206 tools', '206-tool certification', 'Repo operational suite (real stdio JSON-RPC)', 'Every new tool must earn operational evidence', 'td_* case added to runner; 306/306 tools PASS + CERTIFIED with captured JSON-RPC evidence', ['scripts/run-operational-suite.js', 'operational-tests/tools/*'], 'medium', 'low', 'Full-surface operational certification', 'operational-acceptance test (derives count from registry)', 'operational reports', '12.0', 'P0', 'IMPLEMENTED', '306/306'),

  // ---- Architecture & integration (91-100) ----
  E('M01', 'Intelligence-domain-oriented module structure', 'architecture', 'Feature-oriented src/ mixed concerns', 'core/forensics/devtools tangle', 'Roadmap §38 folder structure', 'Domains must own boundaries: kernel/temporal/evidence/...', 'src/intelligence/ with 18 domain modules, each with public barrel + typed exports', ['src/intelligence/*'], 'medium', 'medium', 'Explicit architectural boundaries (SOLID where justified)', 'typecheck + module graph', 'none', '4.0', 'P1', 'IMPLEMENTED'),
  E('M02', 'Backward-compatible facade integration', 'architecture', 'Rewrites break consumers', 'None', 'Roadmap §54 compatibility facades', 'v4 kernel must sit UNDER existing dt_/fx_/base surfaces without breaking them', 'td_* dispatched first in MCPToolsHandler; 121 legacy names + 206 legacy tools preserved (tested)', ['mcp/tools-handler', 'mcp/tools-definition'], 'medium', 'high', 'Zero legacy breakage: 295/295 tests green including all legacy suites', 'tests legacy suites', 'none', '4.0', 'P0', 'IMPLEMENTED', '295/295'),
  E('M03', 'Event-envelope schema versioning', 'architecture', 'Event schema had no version negotiation', 'schemaVersion existed unused', 'MCP evolution practice; roadmap schema versioning', 'Format evolution needs explicit versions', 'EVENT_SCHEMA_VERSION + envelope schemaVersion + .tdom compatibility block', ['kernel/events', 'incident/format'], 'low', 'low', 'Versioned, negotiable event format', 'tests import compatibility', 'none', '4.0', 'P2', 'IMPLEMENTED'),
  E('M04', 'Authoritative version registry', 'architecture', 'Version strings drifted (v2.1.0 banner vs 3.1.0 package)', 'sea-entry printed v2.1.0/43 tools', 'Baseline doc-drift defect', 'One source of truth for version across package/CLI/MCP/artifacts', 'src/intelligence/version.ts: TELEDOM_VERSION + VERSION_HISTORY (v4→v12); sea-entry banner derives from it', ['v12/version', 'sea-entry', 'package.json'], 'low', 'low', 'Version drift structurally eliminated', 'tests version sync assertions', 'none', '12.0', 'P0', 'IMPLEMENTED'),
  E('M05', 'Generated compatibility matrix', 'compatibility', 'Compatibility was hand-claimed', 'README claims', 'Roadmap §59 generated matrices', 'Compatibility must be computed, not asserted', 'generateCompatibilityMatrix(): 100 rows with schema/behavior parity, browser support, simulation, test status', ['registry/compatibility'], 'medium', 'low', 'Machine-generated compatibility truth', 'tests matrix test', 'none', '12.0', 'P1', 'IMPLEMENTED'),
  E('M06', 'Registry-validated tool set (no inflation)', 'compatibility', 'Tool count was a vanity metric', '206→306 growth without validation', 'Roadmap anti-inflation rules', 'Exactly 100 td_* tools in 10 balanced families, validated structurally', 'validateRegistry(): 100 count, no dupes, td_ prefix, 10-per-category enforced', ['registry/capabilities'], 'low', 'medium', 'Structural guard against feature inflation', 'tests registry validation', 'none', '12.0', 'P0', 'IMPLEMENTED'),
  E('M07', 'P0 sequence bug fix in legacy recorder', 'correctness', 'Baseline P0: id/sequence divergence in every event creation', 'generateEventId() double-advance', 'Roadmap red-flag analysis (direct code inspection)', 'Legacy event integrity must be fixed without breaking behavior', 'generateEventId(prefix, seq?) accepts explicit sequence; all 16 call sites pass their sequence', ['core/*'], 'medium', 'high', 'Legacy events now satisfy the identity invariant; tests stay green', 'typecheck + legacy suites 295/295', 'none', '4.0', 'P0', 'IMPLEMENTED'),
  E('M08', 'Lookup-miss honesty in tool dispatch', 'agent-os', 'Missing references crashed or errored tools', 'None', 'API robustness', 'Unknown incident/branch/hypothesis ids are lookup misses, not failures', 'INCONCLUSIVE with actionable notes instead of FAIL crashes', ['v12/mcp handler'], 'low', 'low', 'Robust, honest tool responses (found by operational suite)', 'operational suite 306/306', 'none', '12.0', 'P2', 'IMPLEMENTED'),
  E('M09', 'Directory-import-free kernel modules', 'architecture', 'Barrel imports broke direct Node execution', 'None', 'Node ESM resolution', 'Kernel must be loadable outside bundlers for scripts/tools', 'Explicit file-relative imports within v4 where scripts consume them', ['src/intelligence/*'], 'low', 'low', 'Runnable in Node, vitest and vite alike', 'operational + vitest runs', 'none', '12.0', 'P2', 'IMPLEMENTED'),
  E('M10', 'Versioned .tdom round-trip compatibility', 'compatibility', 'Session format had no forward-compat story', 'None', 'Artifact longevity', 'Older readers must understand newer artifacts gracefully', 'formatVersion + minReaderVersion + compatibility notes on import', ['incident/format'], 'low', 'low', 'Artifact evolution path defined', 'tests compatibility field', 'none', '12.0', 'P2', 'IMPLEMENTED'),
  // ---- Performance, DX & explicitly classified deferrals (101-108) ----
  E('P01', 'Performance causality tools (long-task/layout trace)', 'performance', 'Profiler outputs were isolated from causal model', 'dt performance traces existed without causal linkage', 'Chrome DevTools performance panel; roadmap performance causality', '"Which network event caused this layout shift" must be answerable', 'td_long_task_trace + td_layout_causality correlate performance events through the causal engine', ['v12/mcp handler'], 'medium', 'low', 'Performance plugged into the same evidence + temporal model', 'tests dispatch tests', 'performance profile', '9.0', 'P1', 'IMPLEMENTED', 'perf profile'),
  E('P02', 'Memory-leak pattern detection', 'performance', 'Memory analysis was manual heap reading', 'heap dominators tooling without pattern detection', 'Heap-snapshot tooling; roadmap memory intelligence', 'Retained-growth patterns need temporal churn analysis', 'td_memory_leak_trace: unmount-ratio analysis over DOM churn (growth signal < 0.3)', ['v12/mcp handler'], 'medium', 'low', 'Leak-pattern signals from recorded sessions', 'tests dispatch test', 'none', '9.0', 'P2', 'IMPLEMENTED'),
  E('P03', 'Render-stability query', 'performance', 'No "when is the page settled" primitive', 'wait_for_dom_stable was heuristic timing', 'Roadmap render stability', 'Agents need to know when state is observationally stable', 'td_render_stability via lastStable(settleMs)', ['temporal/queries', 'v12/mcp handler'], 'low', 'low', 'Deterministic stability point', 'tests dispatch + temporal', 'none', '9.0', 'P2', 'IMPLEMENTED'),
  E('P04', 'Honest UNSUPPORTED for live-only capabilities', 'dx', 'Tools faked or crashed without live browser', 'Some live tools returned misleading results', 'Browser Use false-success class', 'No live adapter means honest UNSUPPORTED with wiring instructions', 'td_interaction_execute/safe_apply/retention_graph return UNSUPPORTED with reason + suggestion', ['v12/mcp handler'], 'low', 'high', 'Capability state honesty (never fake success)', 'tests smoke UNSUPPORTED count', 'none', '12.0', 'P0', 'IMPLEMENTED'),
  E('P05', 'Retention-graph live dependency declared', 'dx', 'Heap retention graphs promised without runtime support', 'None', 'DevTools heap snapshot API requirements', 'Claiming runtime heap edges from recorded sessions would be dishonest', 'td_retention_graph returns UNSUPPORTED (EXPERIMENTAL) until live heap snapshots are wired', ['v12/mcp handler'], 'low', 'low', 'No over-claiming: experimental capability explicitly marked', 'tests smoke', 'none', '12.0', 'P0', 'IMPLEMENTED'),
  E('P06', 'Visual causality never claims proof from pixels', 'visual', 'Screenshot diffs were treated as causal evidence', 'Visual regression tooling implies causation', 'Roadmap visual intelligence limits', 'Visual changes must correlate, never prove', 'td_visual_causality correlates visual/dom/runtime with classification; fidelity gate keeps verdicts INCONCLUSIVE', ['v12/mcp handler', 'simulation/counterfactual'], 'medium', 'medium', 'Visual evidence integrated without epistemic overreach', 'tests fidelity gating', 'none', '9.0', 'P1', 'IMPLEMENTED'),
  E('P07', 'Deterministic runtime replay (full fidelity)', 'replay', 'Counterfactual replay is event-level, not runtime-level', 'Branch replay deterministically reorders recorded events', 'Replay.io deterministic runtime replay (competitor strength)', 'True deterministic JS-runtime replay requires record/replay browser instrumentation', 'DEFERRED: requires a forked browser runtime (Replay.io-class infrastructure) — documented as explicit gap, not claimed', ['docs/intelligence limitations'], 'high', 'high', 'Honest boundary declaration instead of over-claim', 'docs limitation section', 'none', '13-preview', 'P3', 'DEFERRED-external-infrastructure'),
  E('P08', 'Cross-browser (Firefox/WebKit) kernel parity', 'compatibility', 'Kernel is exercised on Chrome/Chromium surface', 'Extension + CDP are Chrome-first', 'Playwright cross-browser matrix; roadmap cross-browser strategy', 'Firefox/WebKit need explicit capability status, not assumed parity', 'DEFERRED: browser-specific adapters required; td surfaces report per-mode support; no universal-compat claim', ['docs/intelligence limitations'], 'high', 'medium', 'No false universality claims', 'compatibility matrix modes', 'none', '13-preview', 'P3', 'DEFERRED-platform-limit'),
];

/** Validation: at least 100 DISTINCT, NON-TRIVIAL improvements. */
export function validateImprovements(): { valid: boolean; count: number; problems: string[] } {
  const problems: string[] = [];
  const ids = IMPROVEMENTS.map((i) => i.id);
  if (ids.length < 100) problems.push(`expected at least 100 improvements, found ${ids.length}`);
  const dupes = ids.filter((id, i) => ids.indexOf(id) !== i);
  if (dupes.length) problems.push(`duplicate ids: ${dupes.join(', ')}`);
  const trivial = IMPROVEMENTS.filter((i) => i.title.length < 10 || i.problem.length < 20 || i.why.length < 20);
  if (trivial.length) problems.push(`trivial entries: ${trivial.map((t) => t.id).join(', ')}`);
  return { valid: problems.length === 0, count: IMPROVEMENTS.length, problems };
}

export function improvementsByStatus(): Record<ImprovementStatus, number> {
  const out: Record<string, number> = {};
  for (const i of IMPROVEMENTS) out[i.status] = (out[i.status] ?? 0) + 1;
  return out as Record<ImprovementStatus, number>;
}
